[package]
name = "watos-vfs"
version = "0.1.0"
edition = "2021"
description = "WATOS Virtual File System layer"

[dependencies]
spin = "0.5.2"
watos-path = { path = "../../core/path" }
watos-syscall = { path = "../../core/syscall" }
