[package]
name = "watos-driver-pci"
version = "0.1.0"
edition = "2021"
description = "PCI bus driver for WATOS"

[dependencies]
watos-driver-traits = { path = "../../traits" }
spin = "0.5.2"

[features]
default = []
debug = ["watos-driver-traits/debug-bus"]
