[package]
name = "shell"
version = "0.1.0"
edition = "2021"

[dependencies]
watos-syscall = { path = "../../core/syscall" }
watos-readline = { path = "../../sys/readline" }

[[bin]]
name = "shell"
path = "src/main.rs"

